/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Order = IDL.Record({
  'id' : IDL.Nat,
  'service' : IDL.Text,
  'package' : IDL.Text,
  'customerWhatsApp' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'quantity' : IDL.Text,
  'price' : IDL.Text,
  'profileUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
  'listOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'service' : IDL.Text,
    'package' : IDL.Text,
    'customerWhatsApp' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'quantity' : IDL.Text,
    'price' : IDL.Text,
    'profileUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
    'listOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };